### ISSUE TITLE
请问怎么把爬到的信息分到两个表存储

### ISSUE THREAD

**Issue by fireworksfly** [dataabc/weibo-search#108]
就是把除了id和正文的其他信息放在另外一个csv表？（scrapy刚入门，我不太会改程序，一报它就报错(菜鸡哭泣。。)）

**Comment by dataabc** [comment]
修改pipelines.py的Csvpipeline，它负责csv操作，你可以仿造它改成两个，部分信息用第一个，部分信息用第二个，然后在settings.py的ITEM_PIPELINES添加对应名称就可以了。

**Comment by fireworksfly** [comment]
大佬回复也太快了吧，感谢！我试试。
