### ISSUE TITLE
搜索的关键词中不可以同时包含中文和英文吗，如果同时存在就没结果怎么办

### ISSUE THREAD

**Issue by Yangyehong** [dataabc/weibo-search#116]

**Comment by cloudy-sfu** [comment]
经测试, 同时存在中文和英文关键词, 可以搜索到结果.

**Comment by Yangyehong** [comment]
> 经测试, 同时存在中文和英文关键词, 可以搜索到结果.

你搜索测试用的是什么关键词呢。我用的是 #edg夺冠flag#这样的

**Comment by dataabc** [comment]
#edg夺冠#是有结果的，#edg夺冠flag#即便在微博上搜索也没有结果，程序模拟的就是这个，如果没有结果是正常的。

**Comment by Yangyehong** [comment]
> #edg夺冠#是有结果的，#edg夺冠flag#即便在微博上搜索也没有结果，程序模拟的就是这个，如果没有结果是正常的。

感谢。我刚才发现这个话题被封了，应该和这个话题自己有关
