### ISSUE TITLE
您好，我运行就直接结束了，什么也不输出，请问这是为什么呀？

### ISSUE THREAD

**Issue by shanjinzhi** [dataabc/weibo-search#119]

**Comment by cloudy-sfu** [comment]
输出结果在 “结果文件” 目录下。

**Comment by dataabc** [comment]
是不是之前运行过并强制退出了？如果是，删除crawls文件夹再运行就可以。

**Comment by shanjinzhi** [comment]
是的，已经可以运行了，非常感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dataabc/weibo-search"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月16日(星期二) 下午4:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dataabc/weibo-search] 您好，我运行就直接结束了，什么也不输出，请问这是为什么呀？ (Issue #119)





 
是不是之前运行过并强制退出了？如果是，删除crawls文件夹再运行就可以。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
