### ISSUE TITLE
大佬你好，爬取小白。关于爬取后数据存储的问题

### ISSUE THREAD

**Issue by wenhaolove** [dataabc/weibo-search#129]
我运行程序爬取数据后存储在excel表格中，但是不是分列存储的，而是全部数据存储在一列，我看了看后期也没有办法分列，想请问一下这个问题要怎么解决啊。谢谢。

**Comment by cloudy-sfu** [comment]
从这一行开始：

https://github.com/dataabc/weibo-search/blob/a047bd712220da27e5bb309d2dade6100544810e/weibo/settings.py#L17

确保
```
ITEM_PIPELINES = {
    'weibo.pipelines.DuplicatesPipeline': 300,
    'weibo.pipelines.CsvPipeline': 301,
}
```
这个时候输出的结果是csv文件（而不是xlsx文件），数据是可以分列的。

**Comment by wenhaolove** [comment]
谢谢大佬，数据已经分列，是我自己没搞清楚，麻烦啦
