### ISSUE TITLE
😂大神我有问题要咨询您，就是服务器上面怎么跑这个任务呀

### ISSUE THREAD

**Issue by collinsyu** [dataabc/weibo-search#13]
现在如果在自己开发的机器上，有浏览器，可以获得cookie，但是  放到服务器（ubuntu server 没界面没有浏览器）上，cookie还可以用吗？host不一样了呀。这个可咋整呢

**Comment by dataabc** [comment]
cookie在不同服务器上是通用的，你在一台机器上获取cookie，该cookie也可以在另一台机器上使用

**Comment by collinsyu** [comment]
谢谢谢 ，我试过了，本来想关掉这个的，没来得及
