### ISSUE TITLE
安装scrapy报错

### ISSUE THREAD

**Issue by DeanShiDirect** [dataabc/weibo-search#132]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mitmproxy 7.0.4 requires h2<5,>=4.0, but you have h2 3.2.0 which is incompatible.
mitmproxy 7.0.4 requires hyperframe<7,>=6.0, but you have hyperframe 5.2.0 which is incompatible.

但是这个好像没有什么影响 直接在cmd运行 结果自动导出 csv文件，半成功吧。
最开始是从 https://github.com/dataabc/weibo-crawler   https://github.com/dataabc/weiboSpider  视频爬虫，作者举一反三，搜索爬虫，厉害

**Comment by cloudy-sfu** [comment]
```
pip uninstall h2
pip install h2==4.0
pip uninstall hyperframe
pip install hyperframe==6.0
```

**Comment by DeanShiDirect** [comment]
> 
谢谢回复。

根据操作 pip install h2==4.0 成功安装但是冲突了

Successfully uninstalled hpack-3.0.0

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
scrapy 2.5.1 requires h2<4.0,>=3.0, but you have h2 4.0.0 which is incompatible.
Successfully installed h2-4.0.0 hpack-4.0.0 hyperframe-6.0.1


安装pip install hyperframe==6.0  这个没问题

**Comment by cloudy-sfu** [comment]
你可以尝试更新scrapy, 不过一般来说, 如果程序能运行就不要动了, 函数库多了难免有点兼容问题.

**Comment by DeanShiDirect** [comment]
感谢解惑
