### ISSUE TITLE
关于无法获取点赞数的问题

### ISSUE THREAD

**Issue by po-d** [dataabc/weibo-search#133]
### 运行代码发现获取不到每条微博的点赞数，改了一下下面的就可以了

将weibo\spiders\search.py 423行的
```
attitudes_count = sel.xpath(
                    './/span[@class="woo-like-count"]/text()').extract_first()
```
改为
```
attitudes_count = sel.xpath(
                    './/a[@action-type="feed_list_like"]/em/text()').extract_first()
```

**Comment by cloudy-sfu** [comment]
但是上一次就是 feed_list_like 无法获取点赞数, 才改成 woo-like-count 的.

参考提交: https://github.com/dataabc/weibo-search/commit/87db334ada19964815a0aa1727c075a3f8a1ba5d

**Comment by po-d** [comment]
那可能是最近又改回来了？ 我改成&nbsp;feed_list_like&nbsp;就可以了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dataabc/weibo-search"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月4日(星期六) 下午3:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dataabc/weibo-search] 关于无法获取点赞数的问题 (Issue #133)





 
但是上一次就是 feed_list_like 无法获取点赞数, 才改成 woo-like-count 的.
 
参考提交: 87db334
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by po-d** [comment]
关键词是考研数学，搜索时间是2021-11-03，没有修改其余配置。结果如下





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dataabc/weibo-search"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月4日(星期六) 下午3:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dataabc/weibo-search] 关于无法获取点赞数的问题 (Issue #133)





 
但是上一次就是 feed_list_like 无法获取点赞数, 才改成 woo-like-count 的.
 
参考提交: 87db334
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by po-d** [comment]
关键词是考研数学，时间是2021-12-3，没有修改其他配置。

![bc657b8ba5a118bf1cae4e6e85ff6172](https://user-images.githubusercontent.com/95470997/144708383-ad7a3546-a307-43a3-aecf-1271ae5e4b3e.jpg)

**Comment by cloudy-sfu** [comment]
<image width="400px" src="https://user-images.githubusercontent.com/41314224/144708697-d01e30f0-e4a9-42a9-ac23-809abed49cdd.png">

我查看了, 现在微博的API如上图所示, 还是 span -> woo-like-count 

你登录的可能不是新版微博? 如果不是, 请尝试登录新版微博后复制cookies. **经测试, 新旧版的URL完全一致, 微博服务器根据Cookies区分你访问的版本.**

旧版:

<image width="400px" src="https://user-images.githubusercontent.com/41314224/144708765-ac867ec5-5cef-438e-98b4-03109cf15f96.png">

新版:

<image width="400px" src="https://user-images.githubusercontent.com/41314224/144708726-226ff5fb-9a97-4eb6-86ad-8153ef30c0e4.png">

**Comment by po-d** [comment]
谢谢您的回答，确实是这个问题，我刚刚试了一下用新版的cookie爬取，用您的程序没有问题；对于旧版的话就是feed_list_like
但我是按照您README里的方法获取的cookie，不知道为啥就获取到旧版的cookie了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dataabc/weibo-search"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月4日(星期六) 晚上8:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dataabc/weibo-search] 关于无法获取点赞数的问题 (Issue #133)





 

 
我查看了, 现在微博的API如上图所示, 还是 span -&gt; woo-like-count
 
你登录的可能不是新版微博? 如果不是, 请尝试登录新版微博后复制cookies. 经测试, 新旧版的URL完全一致, 微博服务器根据Cookies区分你访问的版本.
 
旧版:
 

 
新版:
 

 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cloudy-sfu** [comment]
对不起, 我们的 README 文件还没有更新到最新版本的微博.

**Comment by po-d** [comment]
十分感谢您耐心的解答，祝您工作顺利

**Comment by cloudy-sfu** [comment]
已更新说明文档.
