### ISSUE TITLE
大大我想做一个数据分析的作业，但是用您的代码扒取微博没有点赞数、评论数，地区也几乎没有，有什么办法吗，救救我

### ISSUE THREAD

**Issue by zbb1234zz** [dataabc/weibo-search#139]

**Comment by zbb1234zz** [comment]
![屏幕截图 2022-01-01 110837](https://user-images.githubusercontent.com/96931130/147843176-15685fef-4286-4aec-a75a-220d71eab4c6.jpg)

**Comment by cloudy-sfu** [comment]
Duplication of #133 
Duplication of #98
