### ISSUE TITLE
使用scrapy crawl search -s JOBDIR=crawls/search运行的问题

### ISSUE THREAD

**Issue by banlangen1111** [dataabc/weibo-search#187]
使用scrapy crawl search -s JOBDIR=crawls/search运行无反应，但使用scrapy crawl search可以正常运行，请问该如何处理呢？
![image](https://user-images.githubusercontent.com/63344963/162856799-625aa069-a132-43dc-8ff3-fc65884277b7.png)

**Comment by dataabc** [comment]
说明之前的进度文件不正确，删除crawls文件夹。

**Comment by banlangen1111** [comment]
> 说明之前的进度文件不正确，删除crawls文件夹。

十分感谢大大，问题已解决。
