### ISSUE TITLE
dos窗口运行命令报错

### ISSUE THREAD

**Issue by stay-leave** [dataabc/weibo-search#229]

**Comment by stay-leave** [comment]
我在输入scrapy crawl search -s JOBDIR=crawls/search命令后报错
 File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\queuelib\queue.py", line 228, in pop
    self.f.seek(-size - self.SIZE_SIZE, os.SEEK_END)
builtins.OSError: [Errno 22] Invalid argument
然而我输入scrapy crawl search后却可以正常运行。这个问题出现在我使用第一个命令保存上次的爬取结果之后。请问大佬，我这该怎么解决？

**Comment by dataabc** [comment]
可能是上次没有保存好，可能只能删除记录文件了。

**Comment by stay-leave** [comment]
谢谢大佬的解答
