### ISSUE TITLE
控制台有输出，queue和seen也在一直更新，而结果文件一直无变化

### ISSUE THREAD

**Issue by caicai555** [dataabc/weibo-search#236]
环境：AWS EC2
搜索时间：19-22年
之前运行一直没这样的问题，要么都有更新，要么都不更新
今天遇到这样的情况，控制台一直有输出（nohup文件一直更新），crawls中queue和seen也一直有更新，但结果文件没有更新（约6h）

想先请教一下作者，可能是什么原因造成的？

**Comment by dataabc** [comment]
可能是爬到重复的了，参考 #66

**Comment by caicai555** [comment]
感谢，修改search.py后问题已解决
