### ISSUE TITLE
爬取多天，只获取最后一天第一页的数据

### ISSUE THREAD

**Issue by DeNancy** [dataabc/weibo-search#251]

**Comment by dataabc** [comment]
是否添加了有效cookie？

**Comment by DeNancy** [comment]
> 

感谢作者回复,添加了. 本来是可以正常搜索的, 但是过了几天就出现这样情况了. 但我登录这个微博账号可以正常使用. 原因是cookie过期了. 我重新获取cookie放进去就可以用了
