### ISSUE TITLE
写入 MongoDB 模式下无法保存图片及视频

### ISSUE THREAD

**Issue by MinaAku** [dataabc/weibo-search#276]
首先感谢大佬开源项目，对我非常有帮助，感谢！

一直使用 CSV 写入模式爬取数据，同时保存博文的图片及视频，使用正常，存储完整；
但当切换到 MongoDB 模式再执行程序，过程中每条博文爬取后会报TypeError: 'NoneType' object is not subscriptable（该报错csv 模式下不会出现），但程序仍然会继续进行下去，直到爬取结束；爬取完成后在数据库中也只能找到爬取博文的属性数据，图片及视频文件不知道存储在哪里了，并没有找到。
已在 csv 模式下确认当前 cookie 可用，并在 settings 中将'weibo.pipelines.MongoPipeline': 303以及MONGO_URI = 'localhost'取消注释，并将 csv 模式的配置语句注释掉。

另外想请教，如何将每条博文的记录与保存的图片及视频文件对应起来？image_url 与图片文件名称、video_url 与视频文件名称之间是什么关系呢？

感谢大佬们的付出，谢谢！

**Comment by dataabc** [comment]
pipelines.py文件就包含了mongo和图片等的操作，我目前不方便调试，你可以参考下这个文件，图片等的名字是和微博id相关的，大体是微博id和发布日期的组合，它们和url没有关系。

**Comment by MinaAku** [comment]
感谢作者为社区所做的贡献，Good Job！
