### ISSUE TITLE
设置微博发布位置后，会爬取到其他省/直辖市的微博

### ISSUE THREAD

**Issue by Lan-ce-lot** [dataabc/weibo-search#283]
如图设置REGION为广东，得到的结果

![image](https://user-images.githubusercontent.com/53330071/193996535-4ec6aea5-e611-40f1-ba9c-a6d37fb31b3b.png)

**Comment by Lan-ce-lot** [comment]
好像是微博的问题

**Comment by dataabc** [comment]
之前微博可以按地区搜，后来改版了，所以地区参数失效了，不管地区是什么，都搜的是全部。

**Comment by Lan-ce-lot** [comment]
> 之前微博可以按地区搜，后来改版了，所以地区参数失效了，不管地区是什么，都搜的是全部。

原来如此
