### ISSUE TITLE
cookie无效或已过期的问题

### ISSUE THREAD

**Issue by Kenny-hoho** [dataabc/weibo-search#32]
您好，
运行scrapy crawl search或者scrapy crawl search -s JOBDIR=crawls/search，都是在大概半分钟之后显示cookie无效或已过期；
按照教程已经换过两个账号获取的cookie都是这种情况，请问可能是什么问题。

**Comment by dataabc** [comment]
感谢反馈。

应该就是cookie是过期或无效的。可能获取cookie时跳过了某些步骤，一定要按照README获取。

如果还有问题，欢迎继续讨论

**Comment by Kenny-hoho** [comment]
感谢大佬这么快的回复，原因是我在pycharm里更改cookie时，因提示行过长，在每行后加\换行了，十分感谢！！！

**Comment by dataabc** [comment]
感谢反馈。

这个反馈太好了，有些使用者也有cookie的问题，可能就是上面的愿意，感谢
