### ISSUE TITLE
下载的貌似不是原图

### ISSUE THREAD

**Issue by Chopin68** [dataabc/weibo-search#322]
我通过查看文件夹一张相同的图片。再去微博上查看大图，发现大小和清晰度都有差别，我该修改哪项设置呢？

**Comment by Chopin68** [comment]
> 您可以对比下这两个url是否有规律，如果有，可以修改search.py最后一个方法的图片url获取代码。

是一模一样的链接，但是还是会有大小和清晰度差异，有点困惑了

**Comment by dataabc** [comment]
按理说，点击查看原图的url应该和点击之前不同，确定是对比的点击查看大图鼠标右键的url吗？

**Comment by Chopin68** [comment]
> 按理说，点击查看原图的url应该和点击之前不同，确定是对比的点击查看大图鼠标右键的url吗？

确定的，url也是一样的，但是下来的图就是不一样，下面是我用wget对比的获取的大小
![image](https://user-images.githubusercontent.com/75252160/216208988-443cb07a-b524-4749-8808-7504c67d4c76.png)

![image](https://user-images.githubusercontent.com/75252160/216208814-57307e04-3e3b-4b1c-a552-343779b708f9.png)
![image](https://user-images.githubusercontent.com/75252160/216208857-5047d95f-fb65-4684-825c-6296fca41b87.png)

**Comment by dataabc** [comment]
如果这样，您可以修改piplines.py图片下载代码，改下文件下载方法看看。

**Comment by Chopin68** [comment]
> 如果这样，您可以修改piplines.py图片下载代码，改下文件下载方法看看。

感谢！解决了，我通过urllib.request的方法请求图片，都是原图了
