### ISSUE TITLE
隔了那么几分钟会自动停止执行，无错误显示

### ISSUE THREAD

**Issue by Seven750** [dataabc/weibo-search#374]
scrapy爬取，有数据正常获取和写入，但是隔几分钟就会停止执行，也没错误，就莫名其妙的突然停止了，这是什么原因造成的呢，求问
<img width="587" alt="image" src="https://github.com/dataabc/weibo-search/assets/49111378/ac63b9cd-c11f-4beb-b8a5-dfc6b63f499a">

**Comment by dataabc** [comment]
这个可能是微博的限制或者网络原因。

**Comment by Seven750** [comment]
求问，那如果微博有限制了，譬如说之前爬数据可以，过了一会爬不到数据了，可以怎么样突破这个限制呢，我试过重新更换cookie好像是没用。

**Comment by dataabc** [comment]
可以等几天限制会自动解除，或者换个账号在另一台电脑上运行。
