### ISSUE TITLE
爬取不到数据

### ISSUE THREAD

**Issue by flyinglong** [dataabc/weibo-search#442]
之前一直能够正常运行，但是昨天开始无法获取数据
![problem](https://github.com/dataabc/weibo-search/assets/101964834/1cbe1b1f-b09a-46d6-8d17-e2f6f19505b6)
日志显示[scrapy.extensions.logstats] INFO: Crawled 6 pages (at 6 pages/min), scraped 0 items (at 0 items/min)

**Comment by dataabc** [comment]
感谢反馈，可能是被暂时限制了，一般过几天就可以了，或者您如果方便，可以用别的账号在另一台电脑上运行看看。

**Comment by flyinglong** [comment]
谢谢您，确实和您说的一样，过一段时间又能正常获取数据了。
