### ISSUE TITLE
对 #359 的一些问题

### ISSUE THREAD

**Issue by rhine14586** [dataabc/weibo-search#492]
我今天遇到了和 #359 相同的问题，但我是在爬取几天时候出现log停住不刷新新的记录，此时我ctrl C一次中止程序，等待程序保存位置并结束，再次启动遇到 #359 的情况

该情况为cookie失效，重新填cookie后开始爬取，但是此时程序却没有从上次记录结束时间(2019年)开始

如果我要手动从上次结束时间接着爬取，直接修改settings；里的时间，原来的结果文件会被覆盖还是接下去

**Comment by dataabc** [comment]
不会覆盖，会接下去。

**Comment by rhine14586** [comment]
> 不会覆盖，会接下去。

这种情况下需要删除之前的crawls文件夹吗

**Comment by dataabc** [comment]
要删除。
