### ISSUE TITLE
导出结果不再更新，但仍旧在爬

### ISSUE THREAD

**Issue by Xxiaojinyi** [dataabc/weibo-search#497]
烦请问下，爬了一晚上，但是导出结果没有再更新，但是仍旧在爬，这种情况是已经爬完了？还是出现了什么问题？

**Comment by dataabc** [comment]
感谢反馈，可以参考 #66 。

**Comment by Xxiaojinyi** [comment]
> 感谢反馈，可以参考 #66 。

谢谢，完美解决了
