### ISSUE TITLE
能不能添加一个搜索的微博类型，仅返回包含位置的微博。

### ISSUE THREAD

**Issue by isalie** [dataabc/weibo-search#5]
# 要搜索的微博类型，0代表搜索全部微博，1代表搜索全部原创微博，2代表热门微博，3代表关注人微博，4代表认证用户微博，5代表媒体微博，6代表观点微博
WEIBO_TYPE = 1

能不能添加一个7，仅返回包含位置的微博。

**Comment by dataabc** [comment]
感谢建议，我考虑下，如果可以，稍后会添加

**Comment by isalie** [comment]
非常感谢提供的代码，我也得好好学学，看看能不能自己修改一下。

**Comment by dataabc** [comment]
想了想，认为不能添加这个筛选。

原因是其它筛选是微博本身有的，添加了可以缩短运行时间。而这个选项是没有的，如果要实现，需要先获取全部微博，然后再筛选出包含位置的，比原来的运行时间长。

如果想实现，方法也很简单，修改pipelines.py的DuplicatesPipeline类，它是用来去重的，你可以在process_item方法中加判断，如果location为空就丢弃。你也可以仿照search.py，获得WEIBO_TYPE的值，如果值为7且location为空就丢弃。

事实上，刚刚添加了一个按地区筛选的功能，这个比添加WEIBO_TYPE为7可能更实用。因为位置微博比例不多，但是每一个微博都有发布地区。比如你设置REGION=['北京']，搜索结果全都是发布地区在北京的微博，缺点也很明显，不如位置微博精确。

感谢建议，如果还有其它问题或建议，欢迎继续讨论。

**Comment by isalie** [comment]
我也抓包分析了下，的确直接通过url的组合无法实现筛选location的目标，现在考虑还是直接爬数据，下来后数据清洗的时候再进行。谢谢楼主。

**Comment by isalie** [comment]
我也抓包分析了下，的确直接通过url的组合无法实现筛选location的目标，现在考虑还是直接爬数据，下来后数据清洗的时候再进行。谢谢楼主。
