### ISSUE TITLE
整段抓取微博数与分段搜索结果数不匹配

### ISSUE THREAD

**Issue by steven756284184** [dataabc/weibo-search#6]
我在微博高级搜索页面从2015-07-30到2020-02-29以月份为递增区间搜索某关键词（第一个区间仅为2015-07-30到07-31），把搜索结果页面上方显示的结果条数相加得到的总数为493,032条；而使用weibo-search一次性抓取2015-07-30到2020-02-29的结果条数为119,937条。不太清楚两个数字不匹配的原因。

**Comment by steven756284184** [comment]
P.S. weibo-search的抓取结果数没有剔除转发原文的数量。

**Comment by dataabc** [comment]
是不是二者搜索条件不同，本程序默认搜索的是原创微博，不包括转发。

**Comment by steven756284184** [comment]
配置文件已经修改为`WEIBO-TYPE = 0`不筛选。

**Comment by dataabc** [comment]
请问是通过什么存储方式计数的，csv还是数据库，开始另一种方式前有没有删除之前的数据？
csv是没有去重的，如果上次获取到了，这次再获取，还是会写入文件的，微博数会增加；数据库是有去重的，如果某微博id已经存在，就直接更新数据，微博数不变。

**Comment by steven756284184** [comment]
用csv计数的，因为导入mongodb之后才发现和之前用的weibo-crawler的数据混在一起了。如果csv没去重的话，那相差的数目可能更多了吧……

**Comment by steven756284184** [comment]
更新（不重要）：我把csv去重了一下，如果我操作没错的话，仍然是119,937条，说明没有重复项。

**Comment by dataabc** [comment]
> 用csv计数的，因为导入mongodb之后才发现和之前用的weibo-crawler的数据混在一起了。鉴于csv没去重，那相差的数目可能更多了吧……
相差数目应该缩小了吧，还是我理解错了。
如果第二次没有去重，那csv的数量应该比第一次多，因为包含第一次的结果。第二次的结果应该减去第一次的，才是本次获得的数量。

**Comment by dataabc** [comment]
> 更新（不重要）：我把csv去重了一下，如果我操作没错的话，仍然是119,937条，说明没有重复项。

你的意思是第一次获得119,937，第二次csv有493,032，然后把第二次的csv去重后变成119,937了吗？

**Comment by steven756284184** [comment]
> > 更新（不重要）：我把csv去重了一下，如果我操作没错的话，仍然是119,937条，说明没有重复项。
> 
> 你的意思是第一次获得119,937，第二次csv有493,032，然后把第二次的csv去重后变成119,937了吗？

不是。我重新说一下。

第一次没有真的用weibo-search抓数据，只是以月份为区间用微博高级搜索搜了一下，把搜索结果页面上方显示的条数都记录下来，最后相加得到总数493,032。

第二次是用weibo-search一次性从头抓到尾，csv得到119,937条（包括转发的原微博），没有重复数据。

我只是疑惑为什么得到的数字相差这么多。

**Comment by dataabc** [comment]
因为每次搜索结果有1000条，结合多个条件最多1天可以获得1000万。但是微博分布是不均匀的，比如某地一小时内发布了多于1000条微博，程序也只能获得该地该时的1000条，多的部分获取不到；还有有时会出现明明有微博，搜索结果为空的情况。所以得到的数量可能比实际少。

**Comment by steven756284184** [comment]
明白了，非常感谢！
另外，建议您的几个爬虫程序默认mongodb的Database名可以有所区别，防止我这种鲁莽爬完才发现混在一起的惨剧。。

**Comment by steven756284184** [comment]
还有最后两个问题。
1. 程序的爬取方法是把时间筛选范围分割成每天一爬吗？
2. 您知道“搜索页面显示的条数”是不是真实的结果条数吗（如果每天的结果都在1000万以内）？

**Comment by dataabc** [comment]
> 还有最后两个问题。
> 
> 1. 程序的爬取方法是把时间筛选范围分割成每天一爬吗？
> 2. 您知道“搜索页面显示的条数”是不是真实的结果条数吗（如果每天的结果都在1000万以内）？

1.根据微博数量分。如果搜索结果少于50页，就直接获取；如果等于50页，说明可能多于1000条，需要细分，按天分；如果每天的结果还是等于50页，就按小时分；如果还是等于50页，就按小时-省分；如果还是等于50页，按小时-城市分，这是最小的分配单位；
2.我也不知道是不是真实的，如果它那么显示，我选择相信。还有，很多关键字每天的产生量到不了1000万，除非特别热门的关键词。

**Comment by steven756284184** [comment]
> > 还有最后两个问题。
> > 
> > 1. 程序的爬取方法是把时间筛选范围分割成每天一爬吗？
> > 2. 您知道“搜索页面显示的条数”是不是真实的结果条数吗（如果每天的结果都在1000万以内）？
> 
> 1.根据微博数量分。如果搜索结果少于50页，就直接获取；如果等于50页，说明可能多于1000条，需要细分，按天分；如果每天的结果还是等于50页，就按小时分；如果还是等于50页，就按小时-省分；如果还是等于50页，按小时-城市分，这是最小的分配单位；
> 2.我也不知道是不是真实的，如果它那么显示，我选择相信。还有，很多关键字每天的产生量到不了1000万，除非特别热门的关键词。

感谢。没有其他问题了。
