### ISSUE TITLE
运行报错问题

### ISSUE THREAD

**Issue by 805477481** [dataabc/weibo-search#74]
<img width="701" alt="iShot2021-05-09 20 01 21" src="https://user-images.githubusercontent.com/44319750/117571497-6014ed80-b101-11eb-8bbd-5e273c7a7a9c.png">
<img width="701" alt="iShot2021-05-09 20 01 33" src="https://user-images.githubusercontent.com/44319750/117571499-61deb100-b101-11eb-96a9-e3f62859920d.png">
请问大佬们，这是什么问题呢

**Comment by dataabc** [comment]
参考[https://www.cnblogs.com/cxl-/p/14589155.html]

**Comment by 805477481** [comment]
> 参考https://www.cnblogs.com/cxl-/p/14589155.html

卸载了之后显示缺少openssl，我换成windows试试吧
