### ISSUE TITLE
关于持续爬取的问题

### ISSUE THREAD

**Issue by goxofy** [dataabc/weibo-search#8]
有个问下想咨询一下，关于持续爬取的。

比如我想持续关注某些关键字的微博，如果设定爬取4月21日至4月21日，那么如何实现自动爬取4月22日及以后的新微博呢

**Comment by goxofy** [comment]
或者能否将爬取时间区间的粒度精确到小时，这样就可以通过每小时重启一次爬虫来实现了

**Comment by dataabc** [comment]
你可以把START_DATE和END_DATE注释掉，这样程序就会把它们的值设置成当天的日期。比如你22号执行程序，程序就会把值设置成2020-04-22，爬取22日的微博。然后利用第三方软件让程序每隔一天执行一次就可以

**Comment by goxofy** [comment]
> 你可以把START_DATE和END_DATE注释掉，这样程序就会把它们的值设置成当天的日期。比如你22号执行程序，程序就会把值设置成2020-04-22，爬取22日的微博。然后利用第三方软件让程序每隔一天执行一次（如每天23点59分执行），就可以

谢谢回复，这个明白了。那么能否精确到小时呢，我通过cron设定每小时执行一次爬虫

**Comment by dataabc** [comment]
这个就需要修改search.py了。现在是如果没有获得START_DATE和END_DATE，就把今天的日期作为它们的值，你需要改成今天的日期+小时（小时前面如果有0要去掉，比如4月22号1时要用2020-04-22-1，不要用2020-04-22-01）。修改start_requests方法，以前是获取网页后回调parse方法，现在要改成回调parse_by_hour方法，该方法就是专门获取一小时范围的微博的，大致就想到这些。

**Comment by goxofy** [comment]
> 这个就需要修改search.py了。现在是如果没有获得START_DATE和END_DATE，就把今天的日期作为它们的值，你需要改成今天的日期+小时（小时前面如果有0要去掉，比如4月22号1时要用2020-04-22-1，不要用2020-04-22-01）。修改start_requests方法，以前是获取网页后回调parse方法，现在要改成回调parse_by_hour方法，该方法就是专门获取一小时范围的微博的，大致就想到这些。

明白了！我试一下谢谢

**Comment by goxofy** [comment]
搞定了，感谢！

修改了start_date / end_date / timedelta 和回调函数
