### ISSUE TITLE
为什么微博上的动图GIF格式爬取下来的是JPG的静态图呢？

### ISSUE THREAD

**Issue by chang8888** [dataabc/weibo-search#91]
有没有什么办法可以爬取动态的GIF图片？

**Comment by dataabc** [comment]
因为程序获取微博时动图是jpg格式展示的，这种方法暂时无法获取gif格式。

**Comment by chang8888** [comment]
> 因为程序获取微博时动图是jpg格式展示的，这种方法暂时无法获取gif格式。

通过查看网页源代码，确实搜索后的结果页面里面GIF图片显示的是静态jpg格式的缩略图的地址，但是程序中item['weibo']['pics']数组里面获取的地址是动图的地址呀，csv文件中保存的图片地址也是动图的，不知道为什么PIPELINE下载的却是静态的
其实动态和静态图片地址的区别仅仅是//ww3.sinaimg.cn/thumb150/XXXX.jpg和//ww3.sinaimg.cn/bmiddle/XXXX.gif的区别，即中间的某层目录不一样，而且把最后三个字符gif换成jpg也能下载成功。

**Comment by dataabc** [comment]
感谢反馈。

貌似scrapy默认下载静态图片，如果要下载动图需修改代码，参考[Scrapy 爬取堆糖动态图](https://zhuanlan.zhihu.com/p/81611461)。

**Comment by chang8888** [comment]
> 感谢反馈。
> 
> 貌似scrapy默认下载静态图片，如果要下载动图需修改代码，参考[Scrapy 爬取堆糖动态图](https://zhuanlan.zhihu.com/p/81611461)。

原来是这样，修改后可以下载动图了，谢谢指教。
