### ISSUE TITLE
麻烦问一下大佬，时间间隔控制在多少会比较好一点，我怕被封号

### ISSUE THREAD

**Issue by ShutterZor** [dataabc/weibo-search#96]

**Comment by dataabc** [comment]
这个我也不清楚，间隔越长越好，最好不要使用自己常用的账号。

**Comment by ShutterZor** [comment]
谢谢大佬的回复，才看到消息。最近爬的时候发现还存在一个问题：以2020年3月1日，以“最低工资”为关键词进行数据爬取时，设置地区为“全国”与设置地区为“北京”的结果文件是一模一样的。

**Comment by dataabc** [comment]
感谢反馈，地区参数最近失效了

**Comment by ShutterZor** [comment]
谢谢大佬的回复，目前程序挺稳定的，10s一次连着抓了十年没出问题

**Comment by sdu-LHB0617** [comment]
> 

十年，花了多长时间呢，大约抓了多少条数据？谢谢大佬
